### ISSUE TITLE
PDFs - API and specs

### ISSUE THREAD

**Issue by mayou36** [zfit/zfit#29]
# TODOs:

- [x] sample should return n_draws, (n_draws is currently numbers used to sample from
- [ ] make analytic integration fully work
- [ ] add register_analytic_integral for instance

# open questions:
 1. should `pdf.*integrate*(limits)` (without specifying the normalization range) return the unnormalized probability by default (RooFit behavior)? Or should we request explicitely a 
`norm_range = False`
 like this:
`pdf.*integrate*(limits, norm_range=False)`
resp. 
`pdf.*integrate*(limits, norm_range=(24, 42))`
for a normalized integral

 2. Product*PDF* or Product*Pdf*? and same for others? (or different name?)

 3. `Gauss` or `Normal`?

 4. What other pdfs do we need to implement? Let's make a list here, feel free to directly edit here.

# PDFs to implement

API definition of PDFs come here. Also specify argument names if possible.

## Basic
 - [ ] Normal(loc, scale)
 - [ ] Exponential(ARGNAME? (rate? lambda? :S )
 - [ ] Uniform(low, high)

## Physics
 - [ ] CrystalballPdf
 - [ ] DoubleCrystalballPdf

## Functors
 - [ ] ProductPdf(pdfs, dims=None, frac=None)
have an argument of the dims to multiply in the same dim and add a  
dimension if not in the same dim
- [ ] SumPdf(pdfs, frac)

 - [ ] ConvolutionPDF

## Special
 - [ ] Function
	A simple function that won't be normalized (nor extended?)

**Comment by mayou36** [comment]
@apuignav @rsilvaco I've added a few open questions and pdf API, feel free to edit/comment (and I'll update).

**Comment by mayou36** [comment]
Issue moved to [zfit/zfit-developement #13](https://github.com/zfit/zfit-developement/issues/13) via [**ZenHub**](https://www.zenhub.com/)
